# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recipesModule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('preparation_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('photo', models.ImageField(upload_to=recipesModule.models.user_directory_path)),
                ('author', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('directions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesModule.Direction')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipesModule.Ingredient')),
            ],
        ),
    ]
