# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesModule', '0003_auto_20170506_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipesModule.Direction'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
