# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesModule', '0004_auto_20170513_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(),
        ),
    ]
