# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesModule', '0005_auto_20170529_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(default='Descripcion Corta', max_length=200),
            preserve_default=False,
        ),
    ]
